### ISSUE TITLE
Not registering putts in daily 30

### ISSUE THREAD

**Issue by seventenjake** [natestone/chirrp-issues#1]
After doing an online duel I went back to daily 30 and resumed the session. The app didn't log the putts even tho i got the audio of putts being made. I restarted the app and resumed the session again and still the same issue.

**Comment by natestone** [comment]
Did the putt result screen come up showing the putt itself or only audio?

**Comment by seventenjake** [comment]
only audio

**Comment by natestone** [comment]
When restarting, be sure to slow-swipe up and then kill off the app by flicking up.  That will fully reset the app.  

Then, click to a few different tabs until it stop automatically routing you to the duel or wherever you were last.  It seems like this is due to the new auto-resume system.  I'm probably going to disable that in the short term.

**Comment by natestone** [comment]
Also, if this is hanging you up, it's best to delete the app and re-download the original for a bit.  It takes 2-3 days for approval each time we release a bug fix.

**Comment by seventenjake** [comment]
It worked fine after i killed the app and just did a new session vs a
continue session.

**Comment by natestone** [comment]
I believe this is fixed in v1.5.2 which will release shortly. Note - 1.5.1 will be "expired" so that we can roll 1.5.2.  

I completely rewrote the rendering system and hopefullly vastly improved the the server interaction.  We'll see if this does the trick.

**Comment by seventenjake** [comment]
Hi Nate just installed the new testflight version. I noticed a bluetooth
data error message and then got a white screen for a split second. The
bluetooth connection was lost and the app is asking if I want to continue
with the session. It won't connect to bluetooth again unless I kill the app
and launch it again. So pretty much the same issue that was happening
before.

I'll do some more testing tomorrow and let you know if I notice any other
issues.

**Comment by seventenjake** [comment]
It also seems to crash like this when I tap exit at the end of the daily 30.

**Comment by natestone** [comment]
So, we accidentally left our logging on which is filling up the memory of the device and causing the crash.  

However, I'm curious about other potential causes.  We added a "ping time" checker under "Settings" => "Advanced".  Can you take your device to the location where you putt and see what your ping times are?  

Also, when you get the white screen, does the tab bar (buttons across the bottom) disappear?

iPhone 13, correct?

Thanks!

**Comment by natestone** [comment]
This should be fixed with the new release.  Our expectation is that you can do 10+ Daily30s in a row and the app should not crash.  I'm going to close the issue, but please re-open if you see the problem occurring again.

**Comment by seventenjake** [comment]
The whole screen goes white... can't see the navigation bar when I get the
white screen.

I'm about to take some putts I'll let you know what the ping times are.

And yes iphone 13.

**Comment by natestone** [comment]
Did you ever take any putts?  I didn't see any under your account recently, so I'm wondering if you got the chance or if we're just not getting any communication from your phone to the server.
