### ISSUE TITLE
daily 30

### ISSUE THREAD

**Issue by seventenjake** [natestone/chirrp-issues#2]
The after putt screen for putt 5, 10, 15 are wrong they say next put is 4ft, 6ft, 8ft they should be 6ft after putt 5, 8ft after putt 10 and the random distance after putt 15. Also it's annoying it doesn't show the distance of the putt you are currently on now. If I don't see what the next distance is on the putt results screen i don't know what distance i should be putting from is only the distance for the next putt.

**Comment by natestone** [comment]
I think the results slider is sliding to the wrong position - it's supposed to be showing the next putt on the screen in that slider area.  Should be easy to fix.

I'll address the next putt screen being wrong today as well - should not be a problem.  I'll close the ticket when updated.

**Comment by natestone** [comment]
These are fixed on our development branch and will roll with version 1.5.2.

**Comment by natestone** [comment]
This also seems to be working properly now, so I'll close this issue.  If it recurs, please feel free to reopen the issue or start a new one.
