### ISSUE TITLE
Hurricane

### ISSUE THREAD

**Issue by seventenjake** [natestone/chirrp-issues#3]
When playing hurricane it doesn't advance to the next putt. After making or missing the first putt it stays on the first putt length. I also don't see a score for that putt on the screen after the made/missed putt target screen.

**Comment by natestone** [comment]
Yup - that's an issue.  We rewrote the entire putt response system and must have a bug on that one.  Should be an easy fix.

**Comment by natestone** [comment]
Fixed in 1.7.3 - one line of code missing.
